Feat(ci): Better error messages.

diff --git a/{{ cookiecutter.repo_name }}/.github/workflows/docker_build.yaml b/{{ cookiecutter.repo_name }}/.github/workflows/docker_build.yaml
--- a/{{ cookiecutter.repo_name }}/.github/workflows/docker_build.yaml
+++ b/{{ cookiecutter.repo_name }}/.github/workflows/docker_build.yaml
@@ -11,6 +11,15 @@ jobs:
     steps:
       - uses: actions/checkout@v4
 
+      - name: Check Docker secrets
+        run: |
+          if [ -z "${{ secrets.DOCKER_USERNAME }}" ] || [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
+            echo "ERROR: Docker secrets are missing!"
+            echo "Please add DOCKER_USERNAME and DOCKER_PASSWORD in GitHub Settings → Secrets."
+            exit 1
+          fi
+
+
       - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
